# Site settings
title: Advanced Turf & Lawn Care, LLC
email: travis@advancedturfandlawncare.com
description: > # this means to ignore newlines until "baseurl:"
  Advanced Turf & Lawn Care, LLC
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://advancedturfandlawncare.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
